services:
  prodigy:
    platform: linux/amd64
    build:
      context: .
      args:
        PRODIGY_WHL: prodigy-1.11.7-cp310-cp310-linux_x86_64.whl
    ports:
      - "8080:8080"
    environment:
      PRODIGY_KEY: ${PRODIGY_KEY}
      PRODIGY_HOST: 0.0.0.0
      PRODIGY_PORT: "8080"
      PRODIGY_AUTH_SECRET: ${PRODIGY_AUTH_SECRET}
      PRODIGY_ALLOWED_ORIGINS: http://localhost:8080
    volumes:
      - ./data:/app/data
      # optional: persist DB locally
      # - ./prodigy_db:/home/prodigy/.prodigy
    restart: unless-stopped
    command: >
      bash -lc "prodigy bullying-workflow cyberbullying_dataset /app/data/twitter_parsed_clean.txt -l txt -m en_core_web_sm"
